### PR TITLE
Section 2.6. Files

### PR DESCRIPTION
**Pull request by jurij-jukic**
1. 'The primary way to access files within your node is through the [VFS API](./apis/vfs.md).
The VFS API follows [std::fs](https://doc.rust-lang.org/std/fs/index.html) closely, adding some capabilities checks on paths and some combinatory actions.'

- what do you mean by combinatory actions?

2. This section (2.6. Files) and the next one (2.7. Databases) have 'References' at the bottom. I added some of those links in the text as well (where appropriate). Do you prefer:
- links in text but no references, or
- references but no links in text, or
- both links in text and references?

### CODE REVIEW

**Comment by nick1udwig** [comment]
2: Links in text best; if we can get all the references as links in text, do that only. If there are some left over, keep them in references. Don't need to have them in both places

**Comment by nick1udwig** [comment]
@bitful-pannul can you comment on 1 please?

**Review by nick1udwig — COMMENTED** [review]
Changes so far look good :+1:

**Comment by bitful-pannul** [comment]
> @bitful-pannul can you comment on 1 please?

combinatory actions at first meant combining 2 or more std::fs calls like fs::open() and fs::write_all() into one action like vfs::Write. But this seems less relevant now as most actions map 1 to 1 to std::fs. 

Vfs::AddZip is still a good example, it takes in a .zip, extracts it, and writes every file separately.

**Comment by jurij-jukic** [comment]
@nick1udwig 'combinatory actions' part seems like something that shouldn't be mentioned then. agreed?

**Comment by nick1udwig** [comment]
@jurij-jukic Sounds good :+1:

**Pull request merged**
