### PR TITLE
section 9 clarify

### PR DESCRIPTION
**Pull request by jurij-jukic**
- @jonathan (dont know your github tag)

line 95: i know ssh tunnel needs to be recreated every once in a while, but i'm not sure is it every terminal session, or dev session, or how exactly to specify it

- can you make a copy pasteable link in the hosting, and then we can modify the instructions to reflect that
- can you write a command to check if the hosting tunnel is correctly set? or was it to check something in the browser?

### CODE REVIEW

**Comment by dolled-possum** [comment]
> * @jonathan (dont know your github tag)
> 
> line 95: i know ssh tunnel needs to be recreated every once in a while, but i'm not sure is it every terminal session, or dev session, or how exactly to specify it
> 
> * can you make a copy pasteable link in the hosting, and then we can modify the instructions to reflect that
> * can you write a command to check if the hosting tunnel is correctly set? or was it to check something in the browser?

This is probably worth a discussion!  When we were troubleshooting, I mentioned just typing localhost:9090 into a browser to confirm that the tunnel was patent.  But even with that test, it's worth considering whether or not the "tunnel in a backgrounded session" strategy is the wisest for beginners.  It makes it hard to see what's going on.  If someone fails to create their tunnel properly for whatever reason, the user is likely to try again (which, depending on the reason for the initial error, will just continue to fail), and you can have a whole bunch of orphaned `ssh` processes just sitting there.  If I were writing these instructions for novices, I'd probably just use the command in interactive form so the user could be easily advised to simply exist the session and try again if things seemed to be going wrong, rather than provide instructions on how to `kill <pid>` for their unwanted backgrounded ssh sessions.  @nick1udwig what do you think?

**Comment by nick1udwig** [comment]
Oh man, this is what I was hoping to avoid with a `kit connect`/`kit disconnect`.

As is, this will create a long-lasting ssh tunnel that will live as long as your machine is connected to the internet. I agree this leads to difficulties for newbs to diagnose what goes wrong.

I am fine changing this to be a foregrounded session -- but we need to test is carefully to make sure it works as expected and that the instructions are clear. @jurij-jukic do you want to take a shot at this or should I?

**Comment by nick1udwig** [comment]
Re: proposed changes here, if we're going to put "variables" in the commands, we need to change the prose around 35; probably rip it out and replace it with discussion of the "variables"

**Comment by nick1udwig** [comment]
Ok I'll figure out the commands & write a PR.

**Comment by nick1udwig** [comment]
See #208

**Comment by jurij-jukic** [comment]
merged into #208, closing

**Pull request closed without merging**
