### PR TITLE
Section 2.5. Read and Write to Chain

### PR DESCRIPTION
**Pull request by jurij-jukic**
1. 'In addition to allowing connections directly to WebSocket RPC endpoints'
 - this is both read/write, correct?
 - RPC endpoints is referring specifically to endpoints of EVM based chains? I assume things like infura, alchemy, ... fall under this category, but e.g. chainlink (which provide a bunch of offchain stuff) doesn't. 

2. the word 'provider' seems to be referring to two things
 - runtime module
 - chain access provider
 is there another word for the latter so we could disambiguate it?

### CODE REVIEW

**Review by nick1udwig — APPROVED** [review]
Changes lgtm :+1:

**Comment by nick1udwig** [comment]
@dr-frmr can you please address the Qs in OP?

**Comment by dr-frmr** [comment]
> 1. 'In addition to allowing connections directly to WebSocket RPC endpoints'
> 
> * this is both read/write, correct?

Yes, both

> * RPC endpoints is referring specifically to endpoints of EVM based chains? I assume things like infura, alchemy, ... fall under this category, but e.g. chainlink (which provide a bunch of offchain stuff) doesn't.

Yes

> 2. the word 'provider' seems to be referring to two things
> 
> * runtime module
> * chain access provider
>   is there another word for the latter so we could disambiguate it?

We can clarify by always calling the runtime module `eth:distro:sys` or "provider module", and always calling chain access provider the "RPC provider" or "remote provider"

**Comment by jurij-jukic** [comment]
@dr-frmr can you go through all mentions of 'provider' to make sure the terms have been used correctly?

**Review by dr-frmr — APPROVED** [review]
LGTM

**Pull request merged**
