### PR TITLE
hosted nodes edits

### PR DESCRIPTION
**Pull request by nick1udwig**

### CODE REVIEW

**Comment by jurij-jukic** [comment]
can you merge https://github.com/kinode-dao/kinode-book/pull/209 with this PR? it would be easier to read and reason about

**Comment by nick1udwig** [comment]
@jurij-jukic done

**Comment by jurij-jukic** [comment]
@nick1udwig please check if my changes are clear. otherwise lgtm

**Comment by nick1udwig** [comment]
Thanks for the edits @jurij-jukic

**Pull request merged**
