### PR TITLE
.os to .dev

### PR DESCRIPTION
**Pull request by bitful-pannul**
Initial pass, changed in applicable locations where one might be developing with `kit f`. 

I feel changing it in the general explainer docs might confuse people as mainnet currently is purely .os. 

Warming up to potentially making `kit f` purely .os again

### CODE REVIEW

**Comment by dr-frmr** [comment]
What does the `.dev` change buy us? I thought fake.os was serving everyone fine...

**Comment by nick1udwig** [comment]
I don't know why the change was made, @bitful-pannul will have to address that. I do know from testing that the current state of the fake chain does not allow communication b/w nodes with tlds other than `.dev`.

**Comment by dr-frmr** [comment]
Yeah, the fake chain will need to have a TLZ deployed for whatever we use here. I'm generally indifferent but if @bitful-pannul made the change and is having regrets, change it back now before .dev gets entrenched.

**Comment by dr-frmr** [comment]
@bitful-pannul time to decide -- update docs or switch kit default back to `.os`

**Comment by bitful-pannul** [comment]
> @bitful-pannul time to decide -- update docs or switch kit default back to `.os`

I'll revert and commit to 0.8.0, can just ease the 9 character minimum so fake.os and other short names work as expected

**Pull request closed without merging**
